-- ============================================================================
-- EDUCARE TRACK - SCHEMA ADD/UPDATE COMMANDS
-- Run these SQL commands in Supabase SQL Editor to add missing columns and tables
-- ============================================================================

-- ============================================================================
-- PART 1: ADD MISSING COLUMNS TO EXISTING TABLES
-- ============================================================================

-- Admins table
ALTER TABLE public.admins ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;

-- Guards table
ALTER TABLE public.guards ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE public.guards ADD COLUMN IF NOT EXISTS contact_number text;

-- Clinic Staff table
ALTER TABLE public.clinic_staff ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE public.clinic_staff ADD COLUMN IF NOT EXISTS contact_number text;

-- Clinic Visits table
ALTER TABLE public.clinic_visits ADD COLUMN IF NOT EXISTS parent_notified boolean DEFAULT false;
ALTER TABLE public.clinic_visits ADD COLUMN IF NOT EXISTS parent_notified_at timestamp with time zone;
ALTER TABLE public.clinic_visits ADD COLUMN IF NOT EXISTS teacher_approval boolean;
ALTER TABLE public.clinic_visits ADD COLUMN IF NOT EXISTS teacher_remarks text;

-- Excuse Letters table
ALTER TABLE public.excuse_letters ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();

-- Announcements table
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS priority text;
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS posted_by_admin_id bigint REFERENCES public.admins(id);

-- Notifications table
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS is_urgent boolean DEFAULT false;
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS scheduled_at timestamp with time zone;
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS sender_id bigint;
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS batch_id text;

-- Teachers table
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS is_gatekeeper boolean DEFAULT false;

-- Students table
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS qr_code_data text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS profile_photo_url text;

-- Attendance Logs table (Gatekeeper Phase 4)
ALTER TABLE public.attendance_logs ADD COLUMN IF NOT EXISTS morning_absent boolean DEFAULT false;
ALTER TABLE public.attendance_logs ADD COLUMN IF NOT EXISTS afternoon_absent boolean DEFAULT false;
ALTER TABLE public.attendance_logs ADD COLUMN IF NOT EXISTS partial_absence_notified boolean DEFAULT false;

-- ============================================================================
-- PART 2: CREATE MISSING TABLES
-- ============================================================================

-- Grade Schedules Table
CREATE TABLE IF NOT EXISTS public.grade_schedules (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  grade_level text NOT NULL UNIQUE,
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  late_threshold time without time zone,
  early_cutoff time without time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT grade_schedules_pkey PRIMARY KEY (id)
);

-- Attendance Patterns Table (Gatekeeper Phase 4)
CREATE TABLE IF NOT EXISTS public.attendance_patterns (
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    student_id bigint NOT NULL,
    pattern_type text NOT NULL,
    description text,
    severity text DEFAULT 'low',
    is_resolved boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    resolved_at timestamp with time zone,
    CONSTRAINT attendance_patterns_pkey PRIMARY KEY (id),
    CONSTRAINT attendance_patterns_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);

-- Admin Alerts Table (Gatekeeper Phase 4)
CREATE TABLE IF NOT EXISTS public.admin_alerts (
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    alert_type text NOT NULL,
    title text NOT NULL,
    message text NOT NULL,
    severity text DEFAULT 'medium',
    is_read boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    metadata jsonb DEFAULT '{}'::jsonb,
    CONSTRAINT admin_alerts_pkey PRIMARY KEY (id)
);

-- ============================================================================
-- PART 3: CREATE INDEXES (For Performance)
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_attendance_patterns_student_id ON public.attendance_patterns(student_id);
CREATE INDEX IF NOT EXISTS idx_attendance_patterns_created_at ON public.attendance_patterns(created_at);
CREATE INDEX IF NOT EXISTS idx_admin_alerts_created_at ON public.admin_alerts(created_at);
CREATE INDEX IF NOT EXISTS idx_grade_schedules_grade_level ON public.grade_schedules(grade_level);

-- ============================================================================
-- PART 4: UPDATE EXISTING RECORDS (Set defaults for NULL values)
-- ============================================================================

UPDATE public.admins SET is_active = true WHERE is_active IS NULL;
UPDATE public.guards SET is_active = true WHERE is_active IS NULL;
UPDATE public.clinic_staff SET is_active = true WHERE is_active IS NULL;

-- ============================================================================
-- VERIFICATION: Check all columns exist
-- ============================================================================

SELECT 
    table_name, 
    column_name, 
    data_type 
FROM information_schema.columns 
WHERE table_schema = 'public' 
AND table_name IN ('admins', 'guards', 'clinic_staff', 'clinic_visits', 'excuse_letters', 
                   'announcements', 'notifications', 'teachers', 'students', 'attendance_logs',
                   'grade_schedules', 'attendance_patterns', 'admin_alerts')
ORDER BY table_name, column_name;

-- ============================================================================
-- END OF SCHEMA UPDATES
-- ============================================================================

