-- ============================================================================
-- EDUCARE TRACK - SEED DATA
-- Run these SQL commands in Supabase SQL Editor to populate initial data
-- ============================================================================
-- This seed data is required for the system to function properly
-- ============================================================================

-- ============================================================================
-- SECTION 1: CREATE TABLES (If not already created)
-- ============================================================================

-- Grade Schedules Table
CREATE TABLE IF NOT EXISTS public.grade_schedules (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  grade_level text NOT NULL UNIQUE,
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  late_threshold time without time zone,
  early_cutoff time without time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT grade_schedules_pkey PRIMARY KEY (id)
);

-- Attendance Patterns Table (for gatekeeper phase 4)
CREATE TABLE IF NOT EXISTS public.attendance_patterns (
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    student_id bigint NOT NULL,
    pattern_type text NOT NULL,
    description text,
    severity text DEFAULT 'low',
    is_resolved BOOLEAN DEFAULT FALSE,
    created_at timestamp with time zone DEFAULT now(),
    resolved_at timestamp with time zone,
    CONSTRAINT attendance_patterns_pkey PRIMARY KEY (id),
    CONSTRAINT attendance_patterns_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);

-- Admin Alerts Table (for gatekeeper phase 4)
CREATE TABLE IF NOT EXISTS public.admin_alerts (
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    alert_type text NOT NULL,
    title text NOT NULL,
    message text NOT NULL,
    severity text DEFAULT 'medium',
    is_read BOOLEAN DEFAULT FALSE,
    created_at timestamp with time zone DEFAULT now(),
    metadata jsonb DEFAULT '{}'::jsonb,
    CONSTRAINT admin_alerts_pkey PRIMARY KEY (id)
);

-- ============================================================================
-- SECTION 2: ADD MISSING COLUMNS
-- ============================================================================

-- Add is_active to admins (if not exists)
ALTER TABLE public.admins ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;

-- Add is_active to guards (if not exists)
ALTER TABLE public.guards ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;

-- Add is_active to clinic_staff (if not exists)
ALTER TABLE public.clinic_staff ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;

-- Add contact_number to guards (if not exists)
ALTER TABLE public.guards ADD COLUMN IF NOT EXISTS contact_number text;

-- Add contact_number to clinic_staff (if not exists)
ALTER TABLE public.clinic_staff ADD COLUMN IF NOT EXISTS contact_number text;

-- Add columns to clinic_visits
ALTER TABLE public.clinic_visits ADD COLUMN IF NOT EXISTS parent_notified boolean DEFAULT false;
ALTER TABLE public.clinic_visits ADD COLUMN IF NOT EXISTS parent_notified_at timestamp with time zone;
ALTER TABLE public.clinic_visits ADD COLUMN IF NOT EXISTS teacher_approval boolean;
ALTER TABLE public.clinic_visits ADD COLUMN IF NOT EXISTS teacher_remarks text;

-- Add columns to excuse_letters
ALTER TABLE public.excuse_letters ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();

-- Add columns to announcements
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS priority text;
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS posted_by_admin_id bigint REFERENCES public.admins(id);

-- Add columns to notifications
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS is_urgent boolean DEFAULT false;
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS scheduled_at timestamp with time zone;
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS sender_id bigint;
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS batch_id text;

-- Add columns to teachers
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS is_gatekeeper boolean DEFAULT false;

-- Add columns to students
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS qr_code_data text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS profile_photo_url text;

-- Add columns to attendance_logs (gatekeeper phase 4)
ALTER TABLE public.attendance_logs ADD COLUMN IF NOT EXISTS morning_absent BOOLEAN DEFAULT FALSE;
ALTER TABLE public.attendance_logs ADD COLUMN IF NOT EXISTS afternoon_absent BOOLEAN DEFAULT FALSE;
ALTER TABLE public.attendance_logs ADD COLUMN IF NOT EXISTS partial_absence_notified BOOLEAN DEFAULT FALSE;

-- ============================================================================
-- SECTION 3: SEED ADMIN ACCOUNTS
-- ============================================================================

INSERT INTO public.admins (username, password, full_name, contact_number, is_active) VALUES
('admin', 'admin123', 'System Administrator', '09123456789', true),
('principal', 'principal123', 'School Principal', '09123456780', true),
('registrar', 'registrar123', 'School Registrar', '09123456781', true)
ON CONFLICT (username) DO NOTHING;

-- ============================================================================
-- SECTION 4: SEED TEACHER ACCOUNTS
-- ============================================================================

INSERT INTO public.teachers (teacher_id_text, username, password, full_name, department, contact_number, email, is_active, is_gatekeeper) VALUES
('TCH-001', 'teacher1', 'teacher123', 'Juan dela Cruz', 'Mathematics', '09123456710', 'juan.delacruz@school.edu', true, true),
('TCH-002', 'teacher2', 'teacher123', 'Maria Santos', 'English', '09123456711', 'maria.santos@school.edu', true, false),
('TCH-003', 'teacher3', 'teacher123', 'Pedro Garcia', 'Science', '09123456712', 'pedro.garcia@school.edu', true, false),
('TCH-004', 'teacher4', 'teacher123', 'Ana Reyes', 'Filipino', '09123456713', 'ana.reyes@school.edu', true, false),
('TCH-005', 'teacher5', 'teacher123', 'Luis Mendoza', 'MAPEH', '09123456714', 'luis.mendoza@school.edu', true, false)
ON CONFLICT (username) DO NOTHING;

-- ============================================================================
-- SECTION 5: SEED GUARD ACCOUNTS
-- ============================================================================

INSERT INTO public.guards (guard_id_text, username, password, full_name, assigned_gate, shift_schedule, contact_number, is_active) VALUES
('GRD-001', 'guard1', 'guard123', 'Roberto Torres', 'Main Gate', '06:00 AM - 02:00 PM', '09123456720', true),
('GRD-002', 'guard2', 'guard123', 'Carlos Bautista', 'Side Gate', '02:00 PM - 10:00 PM', '09123456721', true),
('GRD-003', 'guard3', 'guard123', 'Daniel Flores', 'Back Gate', '10:00 PM - 06:00 AM', '09123456722', true)
ON CONFLICT (username) DO NOTHING;

-- ============================================================================
-- SECTION 6: SEED CLINIC STAFF ACCOUNTS
-- ============================================================================

INSERT INTO public.clinic_staff (clinic_id_text, username, password, full_name, role_title, contact_number, is_active) VALUES
('CLN-001', 'nurse1', 'nurse123', 'Nurse Clara', 'School Nurse', '09123456730', true),
('CLN-002', 'nurse2', 'nurse123', 'Nurse Bella', 'Medical Assistant', '09123456731', true)
ON CONFLICT (username) DO NOTHING;

-- ============================================================================
-- SECTION 7: SEED PARENT ACCOUNTS
-- ============================================================================

INSERT INTO public.parents (parent_id_text, username, password, full_name, address, contact_number, relationship_type, is_active) VALUES
('PAR-001', 'parent1', 'parent123', 'Mr. Jose Ramirez', '123 Main St, Barangay 1', '09123456740', 'Father', true),
('PAR-002', 'parent2', 'parent123', 'Mrs. Carmen Ramirez', '123 Main St, Barangay 1', '09123456741', 'Mother', true),
('PAR-003', 'parent3', 'parent123', 'Mr. Manuel Ting', '456 Oak Ave, Barangay 2', '09123456742', 'Father', true),
('PAR-004', 'parent4', 'parent123', 'Mrs. Susan Ting', '456 Oak Ave, Barangay 2', '09123456743', 'Mother', true)
ON CONFLICT (username) DO NOTHING;

-- ============================================================================
-- SECTION 8: SEED CLASSES
-- ============================================================================

INSERT INTO public.classes (grade_level, section_name, strand, adviser_id, room_number, school_year) VALUES
('Grade 7', 'Sapphire', NULL, (SELECT id FROM teachers WHERE username = 'teacher1' LIMIT 1), 'Room 101', '2025-2026'),
('Grade 8', 'Ruby', NULL, (SELECT id FROM teachers WHERE username = 'teacher2' LIMIT 1), 'Room 102', '2025-2026'),
('Grade 9', 'Emerald', NULL, (SELECT id FROM teachers WHERE username = 'teacher3' LIMIT 1), 'Room 103', '2025-2026'),
('Grade 10', 'Diamond', NULL, (SELECT id FROM teachers WHERE username = 'teacher4' LIMIT 1), 'Room 104', '2025-2026'),
('Grade 11', 'STEM-A', 'STEM', (SELECT id FROM teachers WHERE username = 'teacher5' LIMIT 1), 'Room 201', '2025-2026'),
('Grade 11', 'STEM-B', 'STEM', (SELECT id FROM teachers WHERE username = 'teacher1' LIMIT 1), 'Room 202', '2025-2026'),
('Grade 12', 'STEM-A', 'STEM', (SELECT id FROM teachers WHERE username = 'teacher2' LIMIT 1), 'Room 301', '2025-2026'),
('Kinder', 'Sunflower', NULL, (SELECT id FROM teachers WHERE username = 'teacher3' LIMIT 1), 'Room 001', '2025-2026'),
('Grade 1', 'Rose', NULL, (SELECT id FROM teachers WHERE username = 'teacher4' LIMIT 1), 'Room 001', '2025-2026'),
('Grade 2', 'Lily', NULL, (SELECT id FROM teachers WHERE username = 'teacher5' LIMIT 1), 'Room 002', '2025-2026')
ON CONFLICT DO NOTHING;

-- ============================================================================
-- SECTION 9: SEED STUDENTS
-- ============================================================================

INSERT INTO public.students (lrn, student_id_text, full_name, parent_id, class_id, gender, address, emergency_contact, qr_code_data, status) VALUES
-- Students for Grade 7 - Sapphire
('123456789001', 'STU-2025-0001', 'Alden Rivera', (SELECT id FROM parents WHERE username = 'parent1' LIMIT 1), (SELECT id FROM classes WHERE grade_level = 'Grade 7' AND section_name = 'Sapphire' LIMIT 1), 'Male', '123 Main St, Barangay 1', '09123456740', 'STU-2025-0001', 'Enrolled'),
('123456789002', 'STU-2025-0002', 'Bella Cruz', (SELECT id FROM parents WHERE username = 'parent1' LIMIT 1), (SELECT id FROM classes WHERE grade_level = 'Grade 7' AND section_name = 'Sapphire' LIMIT 1), 'Female', '124 Main St, Barangay 1', '09123456741', 'STU-2025-0002', 'Enrolled'),
('123456789003', 'STU-2025-0003', 'Charles Ong', (SELECT id FROM parents WHERE username = 'parent2' LIMIT 1), (SELECT id FROM classes WHERE grade_level = 'Grade 7' AND section_name = 'Sapphire' LIMIT 1), 'Male', '125 Main St, Barangay 1', '09123456742', 'STU-2025-0003', 'Enrolled'),
-- Students for Grade 8 - Ruby
('123456789004', 'STU-2025-0004', 'Diana Lim', (SELECT id FROM parents WHERE username = 'parent3' LIMIT 1), (SELECT id FROM classes WHERE grade_level = 'Grade 8' AND section_name = 'Ruby' LIMIT 1), 'Female', '456 Oak Ave, Barangay 2', '09123456743', 'STU-2025-0004', 'Enrolled'),
('123456789005', 'STU-2025-0005', 'Ethan Uy', (SELECT id FROM parents WHERE username = 'parent3' LIMIT 1), (SELECT id FROM classes WHERE grade_level = 'Grade 8' AND section_name = 'Ruby' LIMIT 1), 'Male', '457 Oak Ave, Barangay 2', '09123456744', 'STU-2025-0005', 'Enrolled'),
-- Students for Grade 9 - Emerald
('123456789006', 'STU-2025-0006', 'Fiona Sy', (SELECT id FROM parents WHERE username = 'parent4' LIMIT 1), (SELECT id FROM classes WHERE grade_level = 'Grade 9' AND section_name = 'Emerald' LIMIT 1), 'Female', '458 Oak Ave, Barangay 2', '09123456745', 'STU-2025-0006', 'Enrolled'),
-- Students for Grade 10 - Diamond
('123456789007', 'STU-2025-0007', 'Gabriel Tan', (SELECT id FROM parents WHERE username = 'parent4' LIMIT 1), (SELECT id FROM classes WHERE grade_level = 'Grade 10' AND section_name = 'Diamond' LIMIT 1), 'Male', '459 Oak Ave, Barangay 2', '09123456746', 'STU-2025-0007', 'Enrolled'),
-- Students for Kinder - Sunflower
('123456789008', 'STU-2025-0008', 'Hannah Bae', (SELECT id FROM parents WHERE username = 'parent1' LIMIT 1), (SELECT id FROM classes WHERE grade_level = 'Kinder' AND section_name = 'Sunflower' LIMIT 1), 'Female', '123 Main St, Barangay 1', '09123456747', 'STU-2025-0008', 'Enrolled'),
-- Students for Grade 1 - Rose
('123456789009', 'STU-2025-0009', 'Ian Castro', (SELECT id FROM parents WHERE username = 'parent2' LIMIT 1), (SELECT id FROM classes WHERE grade_level = 'Grade 1' AND section_name = 'Rose' LIMIT 1), 'Male', '124 Main St, Barangay 1', '09123456748', 'STU-2025-0009', 'Enrolled'),
-- Students for Grade 2 - Lily
('123456789010', 'STU-2025-0010', 'Julia Diaz', (SELECT id FROM parents WHERE username = 'parent3' LIMIT 1), (SELECT id FROM classes WHERE grade_level = 'Grade 2' AND section_name = 'Lily' LIMIT 1), 'Female', '456 Oak Ave, Barangay 2', '09123456749', 'STU-2025-0010', 'Enrolled')
ON CONFLICT (lrn) DO NOTHING;

-- ============================================================================
-- SECTION 10: SEED HOLIDAYS
-- ============================================================================

INSERT INTO public.holidays (holiday_date, description, is_suspended, target_grades) VALUES
('2025-01-01', 'New Year''s Day', true, 'All'),
('2025-01-20', 'Chinese New Year', true, 'All'),
('2025-02-14', 'Valentine''s Day', false, 'All'),
('2025-04-09', 'Araw ng Kagitingan', true, 'All'),
('2025-04-17', 'Maundy Thursday', true, 'All'),
('2025-04-18', 'Good Friday', true, 'All'),
('2025-04-19', 'Black Saturday', true, 'All'),
('2025-04-20', 'Easter Sunday', true, 'All'),
('2025-05-01', 'Labor Day', true, 'All'),
('2025-06-12', 'Independence Day', true, 'All'),
('2025-08-21', 'Ninoy Aquino Day', true, 'All'),
('2025-10-31', 'National Halloween', false, 'All'),
('2025-11-01', 'All Saints'' Day', true, 'All'),
('2025-11-30', 'Bonifacio Day', true, 'All'),
('2025-12-25', 'Christmas Day', true, 'All'),
('2025-12-30', 'Rizal Day', true, 'All'),
('2025-12-31', 'New Year''s Eve', false, 'All')
ON CONFLICT (holiday_date) DO NOTHING;

-- ============================================================================
-- SECTION 11: SEED GRADE SCHEDULES
-- ============================================================================

INSERT INTO public.grade_schedules (grade_level, start_time, end_time, late_threshold, early_cutoff) VALUES
('Kinder', '07:00:00', '15:00:00', '08:00:00', '14:00:00'),
('Grades 1-3', '07:30:00', '15:30:00', '08:30:00', '14:30:00'),
('Grades 4-6', '07:30:00', '15:30:00', '08:30:00', '14:30:00'),
('Grade 7', '07:30:00', '16:00:00', '08:30:00', '15:00:00'),
('Grade 8', '07:30:00', '16:00:00', '08:30:00', '15:00:00'),
('Grade 9', '07:30:00', '16:00:00', '08:30:00', '15:00:00'),
('Grade 10', '07:30:00', '16:00:00', '08:30:00', '15:00:00'),
('JHS', '07:30:00', '16:00:00', '08:30:00', '15:00:00'),
('SHS', '07:30:00', '16:00:00', '08:30:00', '15:00:00')
ON CONFLICT (grade_level) DO NOTHING;

-- ============================================================================
-- SECTION 12: SEED ANNOUNCEMENTS
-- ============================================================================

INSERT INTO public.announcements (title, content, posted_by_admin_id, target_teachers, target_parents, target_guards, target_clinic, priority, created_at) VALUES
('Welcome to School Year 2025-2026', 'Welcome back everyone! We are excited to start another academic year. Please ensure all enrollment requirements are completed.', 
 (SELECT id FROM admins WHERE username = 'admin' LIMIT 1), true, true, true, true, 'Important', now()),
('School Calendar Update', 'The revised school calendar has been posted. Please check the admin dashboard for important dates.',
 (SELECT id FROM admins WHERE username = 'admin' LIMIT 1), true, false, false, false, 'Normal', now()),
('Health and Safety Reminder', 'Please remember to follow all health protocols. Wash your hands regularly and stay home if you are sick.',
 (SELECT id FROM admins WHERE username = 'admin' LIMIT 1), true, true, true, true, 'Important', now()),
('Parent-Teacher Conference', 'The Parent-Teacher Conference is scheduled for next month. Please coordinate with your child''s adviser.',
 (SELECT id FROM admins WHERE username = 'admin' LIMIT 1), true, true, false, false, 'Normal', now())
ON CONFLICT DO NOTHING;

-- ============================================================================
-- SECTION 13: SEED SYSTEM SETTINGS
-- ============================================================================

INSERT INTO public.settings (setting_key, setting_value) VALUES
('school_name', 'Educare Track School'),
('school_year', '2025-2026'),
('school_address', '123 Education Street, Learning City'),
('school_contact', '09123456789'),
('school_email', 'info@educaretrack.edu'),
('attendance_mode', 'qr_code'),
('late_threshold_minutes', '30'),
('early_dismissal_minutes', '60'),
('require_parent_notification', 'true'),
('enable_gatekeeper', 'true'),
('clinic_working_hours', '07:00-17:00'),
('emergency_contact', '911'),
('first_day_of_week', 'Monday'),
('grading_period', 'Quarterly')
ON CONFLICT (setting_key) DO NOTHING;

-- ============================================================================
-- SECTION 14: SEED ID TEMPLATES
-- ============================================================================

INSERT INTO public.id_templates (template_type, settings) VALUES
('student', '{"primaryColor": "#1e40af", "secondaryColor": "#3b82f6", "schoolName": "Educare Track School", "includePhoto": true, "includeQR": true, "includeEmergencyContact": true}'),
('teacher', '{"primaryColor": "#059669", "secondaryColor": "#10b981", "schoolName": "Educare Track School", "includePhoto": true, "includeQR": true}'),
('staff', '{"primaryColor": "#7c3aed", "secondaryColor": "#8b5cf6", "schoolName": "Educare Track School", "includePhoto": true, "includeQR": true}')
ON CONFLICT (template_type) DO NOTHING;

-- ============================================================================
-- SECTION 15: SEED ATTENDANCE LOGS (Sample)
-- ============================================================================

INSERT INTO public.attendance_logs (student_id, log_date, time_in, time_out, status, remarks) VALUES
((SELECT id FROM students WHERE student_id_text = 'STU-2025-0001' LIMIT 1), '2025-01-15', '07:15:00', '15:00:00', 'Present', 'On time'),
((SELECT id FROM students WHERE student_id_text = 'STU-2025-0002' LIMIT 1), '2025-01-15', '07:45:00', '15:00:00', 'Late', 'Arrived late'),
((SELECT id FROM students WHERE student_id_text = 'STU-2025-0003' LIMIT 1), '2025-01-15', '07:30:00', '14:00:00', 'Early Out', 'Permission granted'),
((SELECT id FROM students WHERE student_id_text = 'STU-2025-0004' LIMIT 1), '2025-01-15', '07:30:00', '15:30:00', 'Present', 'On time'),
((SELECT id FROM students WHERE student_id_text = 'STU-2025-0005' LIMIT 1), '2025-01-15', NULL, NULL, 'Absent', 'No notification')
ON CONFLICT DO NOTHING;

-- ============================================================================
-- SECTION 16: SEED CLINIC VISITS (Sample)
-- ============================================================================

INSERT INTO public.clinic_visits (student_id, referred_by_teacher_id, reason, nurse_notes, action_taken, status) VALUES
((SELECT id FROM students WHERE student_id_text = 'STU-2025-0001' LIMIT 1), (SELECT id FROM teachers WHERE username = 'teacher1' LIMIT 1), 'Headache', 'Rest and drink water', 'Paracetamol given', 'Completed'),
((SELECT id FROM students WHERE student_id_text = 'STU-2025-0002' LIMIT 1), (SELECT id FROM teachers WHERE username = 'teacher2' LIMIT 1), 'Stomach ache', 'Observed for 30 minutes', 'Sent to class', 'Completed'),
((SELECT id FROM students WHERE student_id_text = 'STU-2025-0003' LIMIT 1), (SELECT id FROM teachers WHERE username = 'teacher1' LIMIT 1), 'Cut on finger', 'First aid administered', 'Bandage applied', 'Completed')
ON CONFLICT DO NOTHING;

-- ============================================================================
-- SECTION 17: SEED NOTIFICATIONS (Sample)
-- ============================================================================

INSERT INTO public.notifications (recipient_id, recipient_role, title, message, type, is_read) VALUES
((SELECT id FROM teachers WHERE username = 'teacher1' LIMIT 1), 'teacher', 'New Announcement', 'Welcome to School Year 2025-2026', 'announcement', false),
((SELECT id FROM parents WHERE username = 'parent1' LIMIT 1), 'parent', 'School Update', 'Please check the announcements for important updates', 'announcement', false),
((SELECT id FROM admins WHERE username = 'admin' LIMIT 1), 'admin', 'System Alert', 'All systems are running normally', 'system', true)
ON CONFLICT DO NOTHING;

-- ============================================================================
-- VERIFICATION: Check seeded data
-- ============================================================================

SELECT 'admins' as table_name, COUNT(*) as record_count FROM admins
UNION ALL
SELECT 'teachers', COUNT(*) FROM teachers
UNION ALL
SELECT 'guards', COUNT(*) FROM guards
UNION ALL
SELECT 'clinic_staff', COUNT(*) FROM clinic_staff
UNION ALL
SELECT 'parents', COUNT(*) FROM parents
UNION ALL
SELECT 'students', COUNT(*) FROM students
UNION ALL
SELECT 'classes', COUNT(*) FROM classes
UNION ALL
SELECT 'holidays', COUNT(*) FROM holidays
UNION ALL
SELECT 'grade_schedules', COUNT(*) FROM grade_schedules
UNION ALL
SELECT 'announcements', COUNT(*) FROM announcements
UNION ALL
SELECT 'settings', COUNT(*) FROM settings
UNION ALL
SELECT 'id_templates', COUNT(*) FROM id_templates
UNION ALL
SELECT 'attendance_logs', COUNT(*) FROM attendance_logs
UNION ALL
SELECT 'clinic_visits', COUNT(*) FROM clinic_visits
UNION ALL
SELECT 'notifications', COUNT(*) FROM notifications;

-- ============================================================================
-- END OF SEED DATA
-- ============================================================================

